#!/usr/bin/env python3
"""Download verified Free assets from threejsassets.com and embed them in the app bundle.

Raw GLB files are only held inside the CI workspace. The public repository receives a
JavaScript data module so the models are embedded in the shipped game rather than
redistributed as standalone asset files.
"""
from __future__ import annotations

import base64
import datetime as dt
import hashlib
import json
import re
import struct
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATED_DIR = ROOT / "js" / "generated"
DOCS_DIR = ROOT / "docs"

LICENSE_URL = "https://threejsassets.com/license"
LICENSE_NAME = "Free Commercial License"
ASSETS = [
    {
        "key": "carSedan",
        "slug": "car-sedan-01",
        "name": "Car Sedan 01",
        "category": "Vehicles",
        "source": "https://threejsassets.com/assets/car-sedan-01",
        "download": "https://threejsassets.com/download/free/car-sedan-01",
    },
    {
        "key": "taxi",
        "slug": "taxi-01",
        "name": "Taxi 01",
        "category": "Vehicles",
        "source": "https://threejsassets.com/assets/taxi-01",
        "download": "https://threejsassets.com/download/free/taxi-01",
    },
    {
        "key": "daySkyDome",
        "slug": "day-sky-dome",
        "name": "Day Sky Dome",
        "category": "Sky",
        "source": "https://threejsassets.com/assets/day-sky-dome",
        "download": "https://threejsassets.com/download/free/day-sky-dome",
    },
]

HEADERS = {
    "User-Agent": "qoo109-Car asset importer/1.0 (+https://github.com/qoo109/Car)",
    "Accept": "text/html,application/octet-stream,model/gltf-binary,*/*;q=0.8",
}


def fetch(url: str) -> tuple[bytes, str]:
    request = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(request, timeout=45) as response:
        return response.read(), response.headers.get("Content-Type", "")


def verify_free_page(asset: dict[str, str]) -> None:
    page_bytes, content_type = fetch(asset["source"])
    page = page_bytes.decode("utf-8", errors="replace")
    normalized = re.sub(r"\s+", " ", page)
    if "Free Commercial License" not in normalized or "Free" not in normalized:
        raise RuntimeError(f"{asset['name']} is not visibly marked Free Commercial License")
    if asset["name"] not in normalized:
        raise RuntimeError(f"Could not verify asset page identity for {asset['name']}")
    if "text/html" not in content_type.lower():
        raise RuntimeError(f"Unexpected asset page content type: {content_type}")


def parse_glb(data: bytes) -> dict[str, object]:
    if len(data) < 20 or data[:4] != b"glTF":
        raise RuntimeError("Downloaded file is not a GLB (missing glTF magic)")
    version, declared_length = struct.unpack_from("<II", data, 4)
    if version != 2:
        raise RuntimeError(f"Unsupported GLB version {version}")
    if declared_length != len(data):
        raise RuntimeError(f"GLB length mismatch: header={declared_length}, actual={len(data)}")

    json_length, json_type = struct.unpack_from("<II", data, 12)
    if json_type != 0x4E4F534A:
        raise RuntimeError("First GLB chunk is not JSON")
    json_start = 20
    document = json.loads(data[json_start : json_start + json_length].decode("utf-8").rstrip(" \t\r\n\x00"))
    return {
        "version": version,
        "generator": document.get("asset", {}).get("generator", ""),
        "extensionsUsed": document.get("extensionsUsed", []),
        "extensionsRequired": document.get("extensionsRequired", []),
        "meshes": len(document.get("meshes", [])),
        "materials": len(document.get("materials", [])),
        "nodes": len(document.get("nodes", [])),
    }


def write_asset_module(records: list[dict[str, object]], downloaded_at: str) -> Path:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    path = GENERATED_DIR / "threejsassets-free-v91.js"
    payload = {
        record["key"]: {
            "name": record["name"],
            "sourceUrl": record["source"],
            "license": LICENSE_NAME,
            "licenseUrl": LICENSE_URL,
            "sha256": record["sha256"],
            "bytes": record["bytes"],
            "glb": record["glb"],
            "dataUri": "data:model/gltf-binary;base64," + record["base64"],
        }
        for record in records
    }
    source = (
        "// Generated by scripts/import_threejsassets.py. Do not edit manually.\n"
        "// Raw GLBs are not committed; they are embedded here as part of the shipped game.\n"
        f"export const THREEJSASSETS_DOWNLOADED_AT = {json.dumps(downloaded_at)};\n"
        f"export const THREEJSASSETS_FREE = {json.dumps(payload, ensure_ascii=False, separators=(',', ':'))};\n"
        "export default THREEJSASSETS_FREE;\n"
    )
    path.write_text(source, encoding="utf-8")
    return path


def write_license_doc(records: list[dict[str, object]], downloaded_at: str) -> Path:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    path = DOCS_DIR / "threejsassets-free-assets.md"
    lines = [
        "# threejsassets.com Free assets",
        "",
        f"Imported: `{downloaded_at}`",
        "",
        "These assets were selected from the **Free** tier and verified against each public asset page before download.",
        "The repository does not publish the raw `.glb` downloads as standalone files. The build embeds them in the game module.",
        "",
        "## License",
        "",
        f"- Public label: **{LICENSE_NAME}**",
        f"- Terms: {LICENSE_URL}",
        "- Permitted: personal, open-source, educational, client, commercial, game, app, website and shipped-product use; modification and embedding are allowed.",
        "- Restricted: standalone resale, sublicensing, mirroring, sharing, redistribution, repackaging, asset packs, templates, datasets and competing services.",
        "- Attribution: not required by the Free Asset License, but source records are retained here for auditability.",
        "",
        "## Imported models",
        "",
        "| Model | Category | Source | SHA-256 | Bytes | GLB details |",
        "|---|---|---|---|---:|---|",
    ]
    for record in records:
        glb = record["glb"]
        details = (
            f"v{glb['version']}; meshes {glb['meshes']}; materials {glb['materials']}; "
            f"extensions {', '.join(glb['extensionsUsed']) or 'none'}"
        )
        lines.append(
            f"| {record['name']} | {record['category']} | {record['source']} | "
            f"`{record['sha256']}` | {record['bytes']} | {details} |"
        )
    lines.extend(
        [
            "",
            "## Integration",
            "",
            "- Loader: Three.js `GLTFLoader` with `DRACOLoader` for Draco-compressed meshes.",
            "- Vehicles: `Car Sedan 01` is the primary racer; `Taxi 01` is used for yellow/taxi-style rivals.",
            "- Environment: `Day Sky Dome` follows the race camera to keep the clear-weather sky stable.",
            "- Runtime module: `js/v9.1-threejsassets.js`.",
            "- Generated embedded asset module: `js/generated/threejsassets-free-v91.js`.",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def update_index() -> None:
    path = ROOT / "index.html"
    text = path.read_text(encoding="utf-8")
    text = text.replace("V9.0", "V9.1").replace("v=9.0", "v=9.1")
    text = text.replace("THREE.JS GLTF V9.0", "THREE.JS FREE ASSETS V9.1")
    text = text.replace("V9.0 THREE.JS · GLB 車模啟動", "V9.1 FREE GLB 資產啟動")
    text = text.replace("THREE.JS + GLB VEHICLE PIPELINE · V9.0", "THREE.JSASSETS FREE PIPELINE · V9.1")
    text = text.replace(
        "V9.0 已將玩家與 AI 車輛改用 Three.js r184 與 GLTFLoader 載入真正 GLB 模型，保留原本操控、AI、碰撞、六條賽道與晴朗起始。",
        "V9.1 僅採用 threejsassets.com 標示 Free 的 GLB：Car Sedan 01、Taxi 01 與 Day Sky Dome；使用 GLTFLoader／DRACOLoader 載入並保留來源與授權紀錄。",
    )
    text = text.replace("Three.js r184", "Free GLB 車輛")
    text = text.replace("GLTFLoader 車模", "GLTFLoader／DRACOLoader")
    text = text.replace("保留既有遊戲系統", "來源與授權可追溯")
    text = text.replace('src="js/v9-three-cars.js?v=9.1"', 'src="js/v9.1-threejsassets.js?v=9.1"')
    path.write_text(text, encoding="utf-8")


def main() -> None:
    downloaded_at = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()
    records: list[dict[str, object]] = []
    for asset in ASSETS:
        print(f"Verifying Free label: {asset['name']}")
        verify_free_page(asset)
        print(f"Downloading GLB: {asset['download']}")
        data, content_type = fetch(asset["download"])
        glb = parse_glb(data)
        records.append(
            {
                **asset,
                "bytes": len(data),
                "sha256": hashlib.sha256(data).hexdigest(),
                "contentType": content_type,
                "glb": glb,
                "base64": base64.b64encode(data).decode("ascii"),
            }
        )
        print(f"  OK {len(data)} bytes; {glb['meshes']} meshes; {glb['extensionsUsed']}")

    write_asset_module(records, downloaded_at)
    write_license_doc(records, downloaded_at)
    update_index()
    print("Generated embedded asset module, license inventory and V9.1 index update.")


if __name__ == "__main__":
    main()
